import { el, $, announce } from '../utils/dom.js';
import { routes, routeForPath, withBase } from '../config/routes.js';
import { environment } from '../config/environment.js';
import { getPreferences, savePreferences } from '../services/local-storage.service.js';
import { getOllinUrl } from '../services/external-channel.service.js';

const navItems = [['Inicio', routes.home, 'home'], ['Conoce Calpulli', '#que-es-calpulli', 'calpulli'], ['Funciones', '#funciones', 'funciones'], ['Explora UPIICSA', routes.explora, 'explora'], ['Comunidad', '#comunidad', 'comunidad'], ['Proyecto', routes.proyecto, 'proyecto']];
function asset(path) { return withBase(`/${path}`); }
function hrefFor(value) { return value.startsWith('#') && routeForPath() !== 'home' ? withBase(value) : value; }

export function renderShell(current = routeForPath()) {
  const header = el('header', { className: 'site-header' }, [el('div', { className: 'container header-inner' }, [el('a', { className: 'brand', href: routes.home, attrs: { 'aria-label': 'UPIICSA Calpulli, inicio' } }, [el('img', { src: asset('src/assets/brand/logo.png'), alt: 'UPIICSA Calpulli' })]), el('nav', { className: 'main-nav', attrs: { 'aria-label': 'Navegación principal' } }, navItems.map(([label, href, key]) => el('a', { href: hrefFor(href), text: label, attrs: current === key ? { 'aria-current': 'page' } : {} }))), el('div', { className: 'header-actions' }, [el('button', { className: 'theme-button', id: 'theme-toggle', type: 'button', text: '◐', attrs: { 'aria-label': 'Cambiar tema' } }), el('a', { className: 'button', href: current === 'home' ? '#proyecto' : routes.proyecto, text: 'Conoce el proyecto' }), el('button', { className: 'menu-button', id: 'menu-toggle', type: 'button', text: '☰', attrs: { 'aria-label': 'Abrir menú', 'aria-expanded': 'false', 'aria-controls': 'mobile-drawer' } })])]), el('div', { className: 'mobile-drawer', id: 'mobile-drawer', attrs: { hidden: '' } }, [el('nav', { attrs: { 'aria-label': 'Navegación móvil' } }, navItems.map(([label, href]) => el('a', { href: hrefFor(href), text: label }))), el('a', { href: routes.privacidad, text: 'Privacidad' }), el('a', { href: routes.contacto, text: 'Contacto' }), el('a', { className: 'button', href: current === 'home' ? '#proyecto' : routes.proyecto, text: 'Conoce el proyecto' })])]);
  document.body.prepend(el('a', { className: 'skip-link', href: '#contenido-principal', text: 'Saltar al contenido' })); document.body.prepend(header); document.body.append(el('div', { id: 'site-live', className: 'sr-only', attrs: { 'aria-live': 'polite', 'aria-atomic': 'true' } })); setupShell();
}
function setupShell() { const root = document.documentElement; root.dataset.theme = getPreferences().theme || 'system'; const toggle = $('#theme-toggle'); toggle?.addEventListener('click', () => { const next = root.dataset.theme === 'dark' ? 'light' : root.dataset.theme === 'light' ? 'system' : 'dark'; root.dataset.theme = next; savePreferences({ theme: next }); announce(`Tema ${next === 'system' ? 'del sistema' : next} activado`); }); const menu = $('#menu-toggle'); const drawer = $('#mobile-drawer'); menu?.addEventListener('click', () => { const open = !drawer.hidden; drawer.hidden = open; drawer.classList.toggle('open', !open); menu.setAttribute('aria-expanded', String(!open)); menu.setAttribute('aria-label', open ? 'Abrir menú' : 'Cerrar menú'); if (!open) drawer.querySelector('a')?.focus(); }); drawer?.addEventListener('click', (event) => { if (event.target.matches('a')) { drawer.hidden = true; drawer.classList.remove('open'); menu?.setAttribute('aria-expanded', 'false'); } }); }

export function renderFooter() { const ollin = getOllinUrl(); const anchor = (value) => routeForPath() === 'home' ? value : withBase(value); document.body.append(el('footer', { className: 'site-footer' }, [el('div', { className: 'container' }, [el('div', { className: 'footer-grid' }, [el('div', { className: 'prose' }, [el('a', { className: 'brand', href: routes.home }, [el('img', { src: asset('src/assets/brand/logo.png'), alt: 'UPIICSA Calpulli' })]), el('p', { text: 'La comunidad digital de UPIICSA, en desarrollo.' }), el('p', { className: 'muted', text: 'Proyecto en desarrollo para la comunidad UPIICSA.' })]), el('nav', { attrs: { 'aria-label': 'Conoce Calpulli' } }, [el('strong', { text: 'Conoce' }), el('a', { href: anchor('#que-es-calpulli'), text: 'Conoce Calpulli' }), el('a', { href: anchor('#funciones'), text: 'Funciones' }), el('a', { href: routes.explora, text: 'Explora UPIICSA' }), el('a', { href: routes.proyecto, text: 'Proyecto' })]), el('nav', { attrs: { 'aria-label': 'Información' } }, [el('strong', { text: 'Información' }), el('a', { href: routes.privacidad, text: 'Privacidad' }), el('a', { href: routes.contacto, text: 'Contacto' }), ollin ? el('a', { href: ollin, target: '_blank', rel: 'noopener noreferrer', text: 'Conoce Ollin' }) : el('span', { className: 'muted', text: 'Desarrollado dentro del ecosistema Ollin' })])]), el('div', { className: 'footer-bottom' }, [el('span', { text: `Proyecto en desarrollo para la comunidad UPIICSA · © ${new Date().getFullYear()} Calpulli` }), el('a', { href: anchor('#contenido-principal'), text: 'Volver arriba ↑' })])]) ])); }
