import { el, $, announce } from './utils/dom.js';
import { routes, routeForPath } from './config/routes.js';
import { environment } from './config/environment.js';
import { getFunctions, getSpaces, getRoadmap, getFaq } from './services/content.service.js';
import { getContactUrl, getOllinUrl } from './services/external-channel.service.js';
import { renderShell, renderFooter } from './components/shell.js';
import { functionCard, spaceCard, roadmapCard } from './components/cards.js';
import { readCategory, goWithCategory } from './utils/url-state.js';

const stylesheet = document.createElement('link');
stylesheet.rel = 'stylesheet';
stylesheet.href = new URL('./styles/app.css', import.meta.url);
document.head.append(stylesheet);

const functionsData = getFunctions(); const spaces = getSpaces(); const roadmap = getRoadmap();
const asset = (path) => `${(environment.baseUrl || '/').replace(/\/+$/, '')}/${path}`;
function section(className = '', children = [], id = '') { return el('section', { className: `section ${className}`, id }, [el('div', { className: 'container' }, children)]); }
function heading(eyebrow, title, description) { return el('div', { className: 'section-heading' }, [el('span', { className: 'eyebrow', text: eyebrow }), el('h2', { text: title }), description ? el('p', { text: description }) : null]); }
function button(label, href, secondary = false) { return el('a', { className: `button${secondary ? ' secondary' : ''}`, href, text: label }); }
function notice(text) { return el('p', { className: 'notice', text }); }
function frame(eyebrow, title, description, content) { const main = el('main', { id: 'contenido-principal' }, [el('section', { className: 'page-hero' }, [el('div', { className: 'container page-hero-inner' }, [el('span', { className: 'eyebrow', text: eyebrow }), el('h1', { text: title }), el('p', { text: description })])]), ...content]); $('#app').replaceWith(main); return main; }

function conceptSection() { return section('alt anchor-target', [heading('Una comunidad, un mismo espacio', 'Un espacio digital para nuestra comunidad', 'Calpulli nace para reunir la vida universitaria de UPIICSA en un mismo espacio digital. Información institucional, actividades, servicios, ubicaciones y contenidos de la comunidad pueden encontrarse de forma más clara, cercana y accesible.'), el('div', { className: 'concept-layout' }, [el('div', { className: 'prose' }, [el('p', { className: 'notice', text: '¿Por qué Calpulli? Calpulli era una forma de organización comunitaria mesoamericana. El nombre representa lo que buscamos construir: un espacio donde nuestra comunidad pueda encontrarse, informarse y participar.' }), el('div', { className: 'tag-row' }, ['Encontrarnos', 'Informarnos', 'Participar'].map((tag) => el('span', { className: 'tag', text: tag }))), button('Conoce el proyecto', routes.proyecto, true)]), el('div', { className: 'calli-visual' }, [el('img', { src: asset('src/assets/brand/iconclaro.png'), alt: 'Glifo Calli, símbolo conceptual de casa y comunidad' })])])], 'que-es-calpulli'); }
function functionsSection() { return section('anchor-target', [heading('Pensado para el día a día', 'Todo lo que necesitas para vivir UPIICSA con mayor claridad', 'Calpulli reúne accesos y contenidos esenciales para que encontrar información, espacios y oportunidades sea más sencillo.'), el('div', { className: 'grid grid-3 functions-grid', id: 'funciones' }, functionsData.map(functionCard)), notice('Son funciones previstas del proyecto, no servicios disponibles todavía.'), button('Conoce todas las funciones', routes.calpulli, true)]); }
function exploreSection() { return section('dark anchor-target', [heading('Explora UPIICSA', 'Tu escuela también se puede explorar digitalmente.', 'Encuentra lo que necesitas antes de recorrer todo el plantel.'), el('div', { className: 'map-layout' }, [el('div', { className: 'map-visual', role: 'region', attrs: { 'aria-label': 'Vista conceptual del mapa de UPIICSA' } }, [el('div', { className: 'map-pin p1', text: '1' }), el('div', { className: 'map-pin p2', text: '2' }), el('div', { className: 'map-pin p3', text: '3' })]), el('div', { className: 'prose' }, [el('div', { className: 'map-key' }, spaces.map((space) => el('div', { className: 'map-key-item' }, [el('span', { className: 'dot', attrs: { 'aria-hidden': 'true' } }), el('span', { text: space.title })]))), notice('Vista conceptual. La información definitiva del plantel se integrará de forma progresiva.'), button('Explora el mapa', routes.explora, true)])])], 'explora'); }
function comparisonSection() { return section('soft', [heading('Información más cerca', 'Una comunidad tan grande necesita información más fácil de encontrar.', 'Calpulli propone reunir distintos tipos de información en una experiencia clara y accesible.'), el('div', { className: 'comparison' }, [el('article', { className: 'compare-panel' }, [el('h3', { text: 'Hoy consultamos' }), el('ul', {}, ['Distintos canales', 'Distintas áreas', 'Distintos tipos de información'].map((item) => el('li', { text: item })))]), el('article', { className: 'compare-panel' }, [el('h3', { text: 'Con Calpulli' }), el('ul', {}, ['Un punto de acceso', 'Información organizada', 'Categorías claras', 'Consulta sencilla'].map((item) => el('li', { text: item })))])]), el('p', { className: 'notice', style: 'margin-top:1.2rem', text: 'No se trata de reemplazar a la comunidad ni a sus áreas, sino de facilitar el acceso a lo que ya tienen para compartir.' })]); }
function communitySection() { const groups = [['Estudiantes', 'Información, orientación y oportunidades para vivir mejor la experiencia universitaria.'], ['Docentes', 'Un acceso más claro a comunicación, actividades y contenidos relevantes.'], ['Áreas institucionales', 'Canales más directos para acercar información útil a la comunidad.'], ['Comunidad UPIICSA', 'Eventos, cultura, conocimiento e iniciativas que también construyen nuestra escuela.']]; return section('anchor-target', [heading('Hecho para encontrarnos', 'UPIICSA es más que un plantel: es una comunidad.', 'Calpulli busca acercar información, espacios, actividades e iniciativas a quienes forman parte de la vida universitaria.'), el('div', { className: 'grid grid-4' }, groups.map(([title, description]) => el('article', { className: 'community-card' }, [el('h3', { text: title }), el('p', { className: 'muted', text: description })]))), el('p', { className: 'quote', text: 'Nuestra escuela. Nuestra comunidad.' })], 'comunidad'); }
function identitySection() { return section('alt', [heading('Identidad que nos representa', 'Tecnología con identidad mexicana.', 'Calpulli combina la identidad de UPIICSA con una expresión digital contemporánea inspirada en nuestras raíces.'), el('div', { className: 'identity-layout' }, [el('div', { className: 'prose' }, [el('div', { className: 'swatches' }, [el('div', { className: 'swatch jade', text: 'Verde UPIICSA · Institución y comunidad' }), el('div', { className: 'swatch maize', text: 'Amarillo maíz · Conocimiento y crecimiento' }), el('div', { className: 'swatch calli', text: 'Calli · Casa, encuentro y comunidad' }), el('div', { className: 'swatch movement', text: 'Movimiento · Innovación dentro del ecosistema Ollin' })])]), el('div', { className: 'identity-art' }, [el('img', { src: asset('src/assets/brand/logo.png'), alt: 'Logotipo visual de UPIICSA Calpulli' })])])]); }
function ollinSection() { const url = getOllinUrl(); return section('', [el('div', { className: 'ollin-band' }, [el('div', { className: 'prose' }, [el('span', { className: 'eyebrow', style: 'color:var(--yellow)', text: 'Parte de un ecosistema' }), el('h2', { text: 'Desarrollado dentro del ecosistema Ollin.' }), el('p', { text: 'Ollin impulsa infraestructura y servicios digitales mexicanos orientados a conectar comunidades, instituciones y oportunidades.' }), url ? el('a', { className: 'button secondary', href: url, target: '_blank', rel: 'noopener noreferrer', text: 'Conoce Ollin' }) : el('span', { className: 'muted', text: 'Relación conceptual · URL pendiente de confirmación' })]), el('span', { className: 'ollin-symbol', text: 'O' })])]); }
function roadmapSection() { return section('soft anchor-target', [heading('Estado del proyecto', 'Construyendo Calpulli.', 'El proyecto avanza por etapas para convertir una visión de comunidad en una experiencia digital útil y confiable.'), el('div', { className: 'roadmap' }, roadmap.map(roadmapCard)), notice('Las etapas se muestran de forma general y pueden ajustarse conforme avance el proyecto.'), button('Conoce el proyecto', routes.proyecto, true)], 'proyecto'); }
function finalSection() { return section('dark', [el('div', { className: 'final-cta' }, [el('h2', { text: 'UPIICSA es más que un plantel. Es una comunidad.' }), el('p', { text: 'Calpulli busca construir su espacio digital.' }), button('Conoce el proyecto', routes.proyecto), el('a', { className: 'button secondary', href: '#inicio', text: 'Volver al inicio' }), el('span', { className: 'status', text: 'Proyecto en desarrollo para la comunidad UPIICSA' })])]); }

function renderHome() {
  const phone = el('div', { className: 'phone' }, [el('div', { className: 'phone-content' }, [
    el('div', { className: 'phone-logo' }, [el('img', { src: asset('src/assets/brand/iconclaro.png'), alt: '' })]),
    el('strong', { text: 'UPIICSA Calpulli' }), el('div', { className: 'phone-line' }),
    el('div', { className: 'phone-card' }, [el('b', { text: 'Explora tu comunidad' }), el('span', { className: 'muted', text: 'Vista conceptual en preparación' })]),
    el('div', { className: 'phone-card' }, [el('b', { text: 'Servicios y espacios' }), el('span', { className: 'muted', text: 'Información por confirmar' })]),
  ])]);
  const heroCopy = el('div', { className: 'hero-copy' }, [
    el('span', { className: 'eyebrow', text: 'Proyecto en desarrollo para la comunidad UPIICSA' }),
    el('h1', { text: 'Nuestra escuela. Nuestra comunidad. En un mismo lugar.' }),
    el('p', { className: 'lead', text: 'Una plataforma digital para descubrir lo que sucede en UPIICSA, encontrar servicios y espacios, consultar información institucional y mantenerte conectado con tu comunidad.' }),
    el('div', { className: 'hero-actions' }, [button('Conoce Calpulli', '#que-es-calpulli'), button('Explora sus funciones', '#funciones', true)]),
    el('p', { className: 'muted', text: 'Información, espacios, servicios y vida universitaria más cerca de ti.' }),
  ]);
  const hero = el('section', { className: 'hero', id: 'inicio' }, [el('div', { className: 'container hero-grid' }, [heroCopy, el('div', { className: 'hero-visual' }, [phone])])]);
  const main = el('main', { id: 'contenido-principal' }, [hero, conceptSection(), functionsSection(), exploreSection(), comparisonSection(), communitySection(), identitySection(), ollinSection(), roadmapSection(), finalSection()]);
  $('#app').replaceWith(main);
}
function renderCalpulli() { return frame('UPIICSA Calpulli', 'Un espacio digital para nuestra comunidad.', 'Concepto y funciones públicas previstas, sin cuentas ni operaciones activas.', [conceptSection(), functionsSection()]); }
function renderExplora() { const selected = readCategory(); const filtered = selected ? spaces.filter((space) => space.title.toLowerCase().includes(selected.toLowerCase())) : spaces; const select = el('select', { id: 'space-filter', name: 'categoria', attrs: { 'aria-label': 'Filtrar categorías de exploración' } }, [el('option', { value: '', text: 'Todas las categorías' }), ...spaces.map((space) => el('option', { value: space.title, text: space.title, selected: selected === space.title }))]); select.addEventListener('change', () => goWithCategory(routes.explora, select.value)); return frame('Explora UPIICSA', 'Encuentra tu camino.', 'Vista conceptual de categorías y espacios del plantel. La información definitiva se integrará progresivamente.', [section('dark', [el('div', { className: 'toolbar' }, [select, el('span', { className: 'status', text: `${filtered.length} categoría${filtered.length === 1 ? '' : 's'} de ejemplo` })]), el('div', { className: 'grid grid-3' }, filtered.length ? filtered.map(spaceCard) : [el('div', { className: 'empty' }, [el('h2', { text: 'No encontramos esa categoría' }), el('p', { className: 'muted', text: 'Limpia el filtro para volver a ver las categorías disponibles.' }), el('a', { className: 'button', href: routes.explora, text: 'Limpiar filtro' })])]), notice('No se muestran edificios, salones, horarios o coordenadas reales en este staging.'), el('a', { className: 'button secondary', href: `${routes.calpulli}#funciones`, text: 'Volver a funciones' })])]); }
function renderProject() { return frame('Estado del proyecto', 'Construyendo Calpulli.', 'Una hoja de ruta general, sin fechas ni promesas de disponibilidad.', [section('', [el('div', { className: 'roadmap' }, roadmap.map(roadmapCard)), notice('Las etapas pueden ajustarse conforme avance el proyecto.'), el('a', { className: 'button', href: routes.contacto, text: 'Contacto próximamente' })])]); }
function renderPrivacy() { return frame('Información legal', 'Aviso de privacidad.', 'Texto de staging pendiente de proporcionar y validar.', [section('', [notice('Esta entrega no crea cuentas, no solicita datos personales y no incorpora analítica.'), el('div', { className: 'prose' }, [el('p', { text: 'Antes de publicar se debe incorporar el responsable, las finalidades, los derechos aplicables, la versión y un mecanismo de contacto legal aprobado.' }), el('p', { className: 'muted', text: 'Versión de staging · no sustituye asesoría legal.' })])])]); }
function renderContact() { const url = getContactUrl(); return frame('Contacto', 'Conversemos sobre Calpulli.', 'Canal informativo pendiente de responsable y destino confirmado.', [section('', [el('div', { className: 'placeholder' }, [notice('No hay formulario ni correo activo en esta entrega. No introduzcas información personal.'), url ? el('a', { className: 'button', href: url, target: '_blank', rel: 'noopener noreferrer', text: 'Abrir canal externo' }) : el('button', { className: 'button', type: 'button', disabled: true, text: 'Canal próximamente' }), el('a', { className: 'button secondary', href: routes.privacidad, text: 'Leer privacidad' })])])]); }
function renderNotFound() { return frame('404', 'Esta ruta no está disponible.', 'Regresa a UPIICSA Calpulli.', [section('', [el('a', { className: 'button', href: routes.home, text: 'Volver al inicio' })])]); }

const route = routeForPath(); renderShell(route); switch (route) { case 'home': renderHome(); break; case 'calpulli': renderCalpulli(); break; case 'explora': renderExplora(); break; case 'proyecto': renderProject(); break; case 'privacidad': renderPrivacy(); break; case 'contacto': renderContact(); break; default: renderNotFound(); } renderFooter();
